const app=document.querySelector('#app');let me,poll,chosenIds={snack:null,drink:null},adminData;
const api=async(u,o={})=>{const r=await fetch('/api'+u,{credentials:'include',headers:{'Content-Type':'application/json',...(o.headers||{})},...o}),d=await r.json().catch(()=>({message:'伺服器回應錯誤'}));if(!r.ok)throw Error(d.message||'操作失敗');return d};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon=s=>s.image_url?`<img class="snack-image" src="${esc(s.image_url)}" alt="${esc(s.name)}">`:`<span class="food">${s.category==='drink'?'🥤':'🍪'}</span>`;
function login(msg=''){app.innerHTML=`<section class="login"><div class="ticket-head"><div class="brand"><small>CLASS SNACK VOTE</small>今日點心票選</div><p>登入後，為你想吃的點心投下一票。</p></div><form class="form" id="login"><label class="field">帳號<input name="username" required placeholder="student01"></label><label class="field">密碼<input name="password" type="password" required></label><button class="action primary">登入</button><p class="error">${esc(msg)}</p></form></section>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();try{me=(await api('/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).user;load()}catch(x){login(x.message)}}}
function shell(x){return `<div class="shell"><header class="masthead"><div class="brand"><small>CLASS SNACK VOTE</small>今日點心票選</div><div class="userbar">${esc(me.name)}<br><button class="action subtle mini" id="pw">修改密碼</button><button class="action subtle mini" id="out">登出</button></div></header>${x}</div>`}
function common(){document.querySelector('#out').onclick=async()=>{await api('/auth/logout',{method:'POST'});login()};document.querySelector('#pw').onclick=async()=>{const oldPassword=prompt('目前密碼'),newPassword=prompt('新密碼（至少 6 個字元）');if(oldPassword&&newPassword)try{await api('/auth/change-password',{method:'POST',body:JSON.stringify({oldPassword,newPassword})});alert('密碼修改成功')}catch(e){alert(e.message)}}}
const time=v=>v?new Date(v).toLocaleString('zh-TW',{dateStyle:'medium',timeStyle:'short'}):'';
function group(category,title){let a=poll.snacks.filter(s=>s.category===category);return a.length?`<section class="choice-section"><h2>${title} <span class="hint">${chosenIds[category]?'已選擇':'請選一項'}</span></h2><div class="snacks">${a.map(s=>`<button class="snack ${chosenIds[category]===s.id?'selected':''}" data-id="${s.id}" data-category="${category}"><span class="rank">#${s.rank}</span>${icon(s)}<h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><span class="price">${s.price?'$'+s.price:''}</span></button>`).join('')}</div></section>`:''}
function results(){let sections=['snack','drink'].map(category=>{let list=poll.snacks.filter(s=>s.category===category),max=Math.max(...list.map(s=>s.votes),1);return `<section class="choice-section"><h2>${category==='snack'?'點心':'飲料'}排名</h2>${list.map(s=>`<div class="result-row"><strong>#${s.rank}</strong><div><b>${esc(s.name)}</b><div class="bar"><i style="width:${s.votes/max*100}%"></i></div></div><strong>${s.votes} 票</strong></div>`).join('')}</section>`}).join('');return `<section class="results"><h2>投票統計 <span class="hint">${poll.completedVoters||0} / 43 人已完成兩項選擇</span></h2>${sections}</section>`}
function student(){let m={not_started:['尚未開始','投票尚未開始，請等待管理員開放。'],open:['投票進行中','每人可選 1 個點心與 1 杯飲料，開放期間可以修改。'],ended:['投票已結束','本次投票已結束']}[poll.status],info=[poll.pollDate&&`供應日期：${poll.pollDate}`,poll.startAt&&`投票時間：${time(poll.startAt)} ～ ${poll.endAt?time(poll.endAt):'未設定'}`].filter(Boolean).join('　｜　'),ready=chosenIds.snack&&chosenIds.drink;let choose=poll.status==='open'?`${group('snack','選點心')}${group('drink','選飲料')}<div class="actions"><span class="hint">${ready?'點心與飲料都已選好，可隨時點選其他品項修改。':'請各選一個點心與飲料；選擇後會立即儲存。'}</span></div>`:`<div class="notice">${m[1]}</div>`;app.innerHTML=shell(`<section class="ticket"><div class="ticket-head"><h1>${poll.status==='ended'?'結果揭曉':'投票時間'}</h1><p>${info||m[1]}</p></div><div class="content"><div class="status ${poll.status}"><i class="dot"></i>${m[0]}</div>${choose}${poll.status!=='not_started'?results():''}</div></section>`);common();document.querySelectorAll('.snack').forEach(b=>b.onclick=()=>vote(+b.dataset.id,b.dataset.category));}
async function vote(snackId,category){try{poll=await api('/poll/vote',{method:'POST',body:JSON.stringify({snackId})});chosenIds={...chosenIds,...poll.selectedSnackIds,[category]:snackId};student()}catch(e){alert(e.message)}}
const local=v=>v?v.slice(0,16):'';
function admin(){let state={not_started:'尚未開始',open:'投票中',ended:'已結束'};app.innerHTML=shell(`<section class="ticket"><div class="ticket-head"><h1>投票控制台</h1><p>設定供應日期、投票時間與每個品項。</p></div><div class="content"><div class="admin-grid"><div class="metric">目前狀態<b>${state[adminData.status]}</b></div><div class="metric">已投票<b>${adminData.votedCount} / ${adminData.studentCount}</b></div><div class="metric">可用選項<b>${adminData.snacks.filter(s=>s.active).length}</b></div></div><section class="admin-section"><h2>供應與投票時間</h2><form class="schedule" id="schedule"><div class="schedule-grid"><label>要吃的日期<input name="pollDate" type="date" value="${esc(adminData.pollDate)}"></label><label>開始投票時間<input name="startAt" type="datetime-local" value="${local(adminData.startAt)}"></label><label>結束投票時間<input name="endAt" type="datetime-local" value="${local(adminData.endAt)}"></label></div><div class="actions"><button class="action primary">儲存時間設定</button><span class="hint">設定後會自動切換投票狀態。</span></div></form></section><div class="actions"><button class="action" data-state="not_started">設為尚未開始</button><button class="action primary" data-state="open">開始投票</button><button class="action danger" data-state="ended">結束投票</button></div><section class="admin-section"><h2>新增品項</h2><form id="add" class="snack-form"><select name="category"><option value="snack">點心</option><option value="drink">飲料</option></select><input name="name" required placeholder="名稱"><input name="description" placeholder="簡短說明"><input name="price" type="number" min="0" placeholder="價格"><input name="image" type="file" accept="image/*"><button class="action primary">新增</button></form><p class="hint">圖片可不傳，最大 2 MB。</p></section><section class="admin-section"><h2>品項與票數</h2><div class="table-wrap"><table class="table"><thead><tr><th>品項</th><th>分類</th><th>票數</th><th>狀態</th><th></th></tr></thead><tbody>${adminData.snacks.map(s=>`<tr><td>${s.image_url?`<img class="preview" src="${esc(s.image_url)}" alt="">`:''}<b>${esc(s.name)}</b><br><span class="hint">${esc(s.description||'')} ${s.price?'$'+s.price:''}</span></td><td>${s.category==='drink'?'飲料':'點心'}</td><td>${s.votes}</td><td>${s.active?'開放':'隱藏'}</td><td><button class="action subtle mini" data-edit="${s.id}">編輯</button></td></tr>`).join('')}</tbody></table></div></section></div></section>`);common();document.querySelector('#schedule').onsubmit=schedule;document.querySelector('#add').onsubmit=add;document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>status(b.dataset.state));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(+b.dataset.edit))}
async function status(s){try{adminData=await api('/admin/status',{method:'PUT',body:JSON.stringify({status:s})});admin()}catch(e){alert(e.message)}}
async function schedule(e){e.preventDefault();try{adminData=await api('/admin/schedule',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});admin()}catch(e){alert(e.message)}}
function image(file){return new Promise((ok,no)=>{if(!file)return ok('');if(file.size>2097152)return no(Error('圖片最大 2 MB'));let r=new FileReader;r.onload=()=>ok(r.result);r.readAsDataURL(file)})}
async function add(e){e.preventDefault();try{let f=new FormData(e.target),b=Object.fromEntries(f);b.imageUrl=await image(f.get('image'));delete b.image;adminData=await api('/admin/snacks',{method:'POST',body:JSON.stringify(b)});admin()}catch(e){alert(e.message)}}
async function edit(id){let s=adminData.snacks.find(x=>x.id===id),name=prompt('名稱',s.name);if(name===null)return;let description=prompt('簡短說明',s.description||'');if(description===null)return;let price=prompt('價格',s.price||'');if(price===null)return;let category=confirm('確定＝點心；取消＝飲料'),active=confirm('確定＝開放；取消＝隱藏'),imageUrl=s.image_url||'';if(confirm('要更換或新增圖片嗎？')){let picker=document.createElement('input');picker.type='file';picker.accept='image/*';picker.onchange=async()=>{try{imageUrl=await image(picker.files[0]);save()}catch(e){alert(e.message)}};picker.click()}else save();async function save(){try{adminData=await api('/admin/snacks/'+id,{method:'PUT',body:JSON.stringify({name,description,price,category:category?'snack':'drink',active,imageUrl})});admin()}catch(e){alert(e.message)}}}
async function load(){try{me=(await api('/auth/me')).user;if(me.role==='admin'){adminData=await api('/admin/dashboard');admin()}else{poll=await api('/poll');chosenIds={snack:null,drink:null,...poll.selectedSnackIds};student()}}catch{login()}}load();
